import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { trpc } from "../utils/trpc";
import { useState } from "react";
import { ShoppingItem } from "@prisma/client";
import ItemModal from "../components/ItemModal";

const Home: NextPage = () => {
  // const hello = trpc.example.hello.useQuery({ text: "from tRPC" });

  const [items, setItems] = useState<ShoppingItem[]>([]);
  const [modal, setModal] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Shopping List</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {modal ? <ItemModal setModal={setModal} />: <></>}

      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Shopping List</h2>
          <button onClick={() => setModal(!modal)} type="button" className="bg-violet-500 text-white text-lg p-2 rounded-md transition hover:bg-violet-800">Add Shopping Item</button>
        </div>

        <ul>
          
          {items.map((item) => (
            <li key={item.id} className="flex justify-between items-center">
              <span>{item.name}</span>
            </li>
          ))}

        </ul>

      </main>
    </>
  );
};

export default Home;
